name: app_environment
channels:
  - snowflake
dependencies:
  - agate=*
  - annotated-types=*
  - asn1crypto=*
  - attrs=*
  - babel=*
  - certifi=*
  - cffi=*
  - click=*
  - colorama=*
  - cryptography=*
  - dbt-extractor=*
  - deepdiff=*
  - filelock=*
  - importlib-metadata=*
  - isodate=*
  - jinja2=*
  - jsonschema=*
  - logbook=*
  - markupsafe=*
  - mashumaro=*
  - more-itertools=*
  - msgpack-python=*
  - networkx=*
  - ordered-set=*
  - packaging=*
  - pathspec=*
  - platformdirs=*
  - protobuf=*
  - pycparser=*
  - pydantic=*
  - pydantic-core=*
  - pyjwt=*
  - pyopenssl=*
  - python-dateutil=*
  - pytz=*
  - pyyaml=*
  - referencing=*
  - requests=*
  - rpds-py=*
  - sqlparse=*
  - text-unidecode=*
  - tomlkit=*
  - typing-extensions=*
  - urllib3=*